### ISSUE TITLE
publishPagination undefined

### ISSUE THREAD

**Issue by thusila** [Kurounin/PaginationExample#2]
import { publishPagination } from 'meteor/kurounin:pagination';

Meteor.publishPagination("Customers",function(){
     filters: {is_enabled: true}
 });

I'm using meteor 1.3 version and I added above code to the publish.js and it shows an error publishPagination is not a method.when running downloaded project it works fine.Let me know whether there is an issue with the version

**Comment by Kurounin** [comment]
Do you have the ecmascript package added to your project?
There shouldn't be an issue with using an older version. Can you try changing the release in the example to 1.3 and see if you get the same error?

**Comment by thusila** [comment]
yeah I have added ecmascript.But when I apply "publishPagination" it shows that there is not such a method

**Comment by Kurounin** [comment]
Can you check the versions file and see if you're using the latest pagination package?

**Comment by thusila** [comment]
yes I' using the latest package 
kurounin:pagination@1.0.24
kurounin:pagination-blaze@1.0.2

**Comment by Kurounin** [comment]
I noticed now the typo in your code. You should use 
```javascript
publishPagination("Customers",function(){
    filters: {is_enabled: true}
});
```
instead of `Meteor.publishPagination`.

**Comment by thusila** [comment]
this is the output -  [object Object]

**Comment by Kurounin** [comment]
Change `Meteor.publishPagination` to simply `publishPagination`.
The code should look like
```javascript
import { publishPagination } from 'meteor/kurounin:pagination';

publishPagination("Customers",function(){
    filters: {is_enabled: true}
});
```

**Comment by thusila** [comment]
ReferenceError: publishPagination is not defined

**Comment by Kurounin** [comment]
Do you have ?
`import { publishPagination } from 'meteor/kurounin:pagination';`

**Comment by Kurounin** [comment]
If this code does not work:
```javascript
import { publishPagination } from 'meteor/kurounin:pagination';

publishPagination("Customers",function(){
    filters: {is_enabled: true}
});
```
it might be because Meteor 1.3 does not support nested imports, in which case you could try writing it like this:

```javascript
import * as pagination from 'meteor/kurounin:pagination';

pagination.publishPagination("Customers",function(){
    filters: {is_enabled: true}
});
```

**Comment by thusila** [comment]
ah right now it is working fine thanks.Can you update this blaze pagination like react-pagination by including search bar and data tables?

**Comment by Kurounin** [comment]
That's not the purpose of this repository, since usage of the search bar would depend on the structure of your collection and a data table can be as simple as using the tables classes from bootstrap to stylize how the documents data is displayed.
For search bar functionality all you need to do is add a handler for the search input onChange event and call `Template.instance().pagination.filters({searched_field: newValue})` to modify the current filters.

**Comment by thusila** [comment]
Ok I'll check it.Thankyou very much

**Comment by thusila** [comment]
I used Template.instance().pagination.filters({searched_field: newValue}) and it get the result if I typed totally existing value.Just think I'm searching a name so if I typed first two three letter it should show the names begins with that.. is this possible to do with this filter

**Comment by thusila** [comment]
how I include below publish inside publishPagination

Meteor.publish('AllCustomers', function(search, hoid, options){

		// Prepare options
		options = _.extend({
			sort: {name: 1},
			skip: 0,
			limit: 10
		}, options);

		let query      = {}
		
		if ( search ) {
			let regex = new RegExp( search, 'i' );

			query = { 'headofficeId':hoid,
			$or: [
			{ name: regex },
			{ telNo: regex }
			]
		};

	}else{
		query = {'headofficeId':hoid};
	}

	return Customers.find( query, options );
});

**Comment by Kurounin** [comment]
Yes, it's possible. You need to build the regex on the client side:
```javascript
if (search) {
    // escape the input text value
    var tmpFilter = search.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g, "\\$&").trim();

    // set the filter using mongo regular expression
    Template.instance().pagination.filters({
        $or: [
            {name: {$regex: tmpFilter, $options: "i"}},
            {telNo: {$regex: tmpFilter, $options: "i"}}
        ]
    });
}

```

**Comment by thusila** [comment]
Thank you very much, it works fine.I'll try to update your blaze example with search option

**Comment by thusila** [comment]
one thing
publishPagination(Customers, {
    filters: {headofficeId: "A7pPhPwobZkG6jLoK"}
    
});
how to pass logged user headofficeId to filter.It should not be static.Need to pass headofficeId parameter to server filter 

publishPagination(Customers, {
    filters: {headofficeId: "A7pPhPwobZkG6jLoK"}
    
});

**Comment by thusila** [comment]
changed the above function like
publishPagination(Customers, function(headofficeId){
    filters: {headofficeId: headofficeId}
    
});
how to pass logged user headofficeId as parameter

**Comment by Kurounin** [comment]
Where do you store headofficeId? Is it as a user profile field? If you want to force the filter for each logged in user, on server side you can do:
```javascript
publishPagination(Customers, {
    dynamic_filters: function () {
        return {headofficeId: Meteor.user().profile.headofficeId};
    }
});
```

**Comment by thusila** [comment]
yes.I want to force the filter for each logged in user, on the server side. I added above code above code is not working.Can server identify the logged user ?

**Comment by thusila** [comment]
headofficeId is in users collection

**Comment by Kurounin** [comment]
Yes, you can identify the current logged in user that subscribed to the publication. If Meteor.users() is not working, you can search for the current user yourself. Try the following
```javascript
publishPagination(Customers, {
    dynamic_filters: function () {
        var user = Meteor.users.findOne(this.userId);

        // or user.profile.headofficeId depending on where you store the information
        return {headofficeId: user.headofficeId};
    }
});
```

**Comment by thusila** [comment]
Great it works thank you

**Comment by thusila** [comment]
In publish
publishPagination(Meteor.users, {
    dynamic_filters: function () {
        // var user = Meteor.users.findOne(this.userId);
        // return {headofficeId: user.profile.headofficeId};
    }
});

user.js
Template.UsersList.onCreated(function(){
  this.pagination = new Meteor.Pagination(Meteor.users, {
       // sort: {
       //      name: 1
       //  }
  });
});

is this the way how I access users table in meteor?

**Comment by Kurounin** [comment]
Yes, `Meteor.users` contains the users collection defined by Meteor.

**Comment by thusila** [comment]
I have used below code inside an autorun and it stuck my application what is the reason for that

this.pagination = new Meteor.Pagination(Customers, {
        sort: {
            name: 1
        }
    });
    this.serviceAndProductPagination = new Meteor.Pagination(Services, {
        sort: {
            name: 1
        }
    });

**Comment by thusila** [comment]
if I change something in the application and above code is not in autorun it will not reactively show the change

**Comment by Kurounin** [comment]
The above code is the initialization of the pagination instance. It's not supposed to be reactive. You should change the filters or any other settings of the initialized pagination instance, separately in a dynamic reactive place.
